# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'kbcuekt' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for kbcuekt
pod 'RealmSwift'
pod 'Google-Mobile-Ads-SDK'

  target 'kbcuektTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'kbcuektUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
